const { MessageEmbed } = require('discord.js');
const colors = require('../colors.json');

const embed = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Thank you for adding QuaBot!")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("You've added quabot to this guild. QuaBot is an advanced bot with loads of features, such as music, welcome messages, logging and a lot more! Configure some basic settings below this message, like logs, welcome messages and more.")
    .addField("Quick Links", `:globe_with_meridians: Website: https://quabot.net\n:robot: Commands: https://wiki.quabot.net/\n<:discord:925674544298098688> Discord: https://discord.gg/Nwu9DNjYa9`)
    .setTimestamp()
const stepOne = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Logging configuration (1/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("When users join a voice channel, a text channel gets deleted, a role gets updated, or an admin command gets run, it will be logged in the logging channel. Logs are enabled by default, would you like to keep them enabled?")
    .setTimestamp()
    .setFooter("Vote below this message.")
const stepOne2 = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Logging configuration (1/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("So, logging is enabled now, but where do you want these messages to go? Mention the channel within 10 seconds.")
    .setTimestamp()
const stepTwo = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Welcome configuration (2/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("When users join a server, a message is sent. QuaBot offers that too, would you like to enable that feaure?")
    .setTimestamp()
    .setFooter("Vote below this message.")
const stepOneTDisabled = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Logs disabled! (1/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("Moving on to section two, welcome messages and join roles.")
    .setTimestamp()
const stepTwoTDisabled = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Welcome messages disabled! (2/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("Moving on to the second part of section two, join roles.")
    .setTimestamp()
const stepToTDisabled = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Join roles disabled! (2/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("Moving on to the third and final part, tickets.")
    .setTimestamp()
const stepTwoChannel = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Welcome configuration (2/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("So, join messages are enabled. But where do you want them to be sent?  Mention the channel within 10 seconds.")
    .setTimestamp()
const stepTwoRoleToggle = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Welcome configuration (2/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("You might have a role like Member, that all users must have to see channels. QuaBot can automatically give users that role! Would you like to enable on join roles?")
    .setTimestamp()
    .setFooter("Vote below this message.")
const stepTwoRole = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Welcome configuration (2/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("So, you have join roles enabled, what role would you like to have as your main role? Send the name withing 10 seconds.")
    .setTimestamp()
const stepThree = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Tickets configuration (3/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("You might want users to ask for support, also known as making tickets. Would you like to enable that module?")
    .setTimestamp()
    .setFooter("Vote below this message.")
const done = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("That's it, you're all setup now!")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("You have run through the basic configuration of quabot. We have other modules like suggestions, reports, polls and some other stuff. You can configure those by using `/config`!\nAgain, thank you for choosing quabot and putting your trust in us. We will make your time with us worth it.")
    .setTimestamp()
const stepThreeMainCat = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Tickets configuration (3/3)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("So, tickets are enabled. The category for Main Tickets will be called `Tickets` by default. If you wish to change this, use `/config`. We will now check to see if this category exists and if it doesn't, we will create it.")
    .setTimestamp()

module.exports = { stepThreeMainCat, done, stepToTDisabled, stepThree, stepTwoRole, embed, stepOne, stepOne2, stepTwo, stepOneTDisabled, stepTwoChannel, stepTwoTDisabled, stepTwoRoleToggle }