const colors = require('../colors.json');
const { MessageEmbed } = require('discord.js');

const noPermission = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTimestamp()
    .setTitle(":x: No permission!")
    .setDescription("To change server settings you need `ADMINISTRATOR` permissions.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png");

const levelDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled Level System succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const levelEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled Level System succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const logDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled Logging System succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const logEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled Logging System succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const roleDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled the Join role system succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const roleEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled the Join role system succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const musicDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled music succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const musicEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled music succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const reportDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled music succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const reportEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled music succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const suggestDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled suggestions succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const suggestEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled suggestions succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const ticketDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled tickets succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const ticketEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled tickets succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const pollsDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled the Polls System succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const pollEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled the Polls System succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const welcomeDisabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled welcome messages succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const welcomeEnabled = new MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled welcome messages succesfully.")
    .addField("Quick Links", "[Invite me](https://discord.com/oauth2/authorize?client_id=845603702210953246&scope=bot%20applications.commands&permissions=346268609631) - [Website](https://quabot.xyz/) - [Discord](https://discord.gg/Nwu9DNjYa9)")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")

const channelLevelDisabled = new MessageEmbed()
    .setTitle("Disabled Level Up Channel")
    .setColor(colors.COLOR)
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setTimestamp()
    .setDescription("Messages will now be sent in the users message channel at that time.")



module.exports = { channelLevelDisabled, welcomeDisabled, welcomeEnabled, pollsDisabled, pollEnabled, ticketDisabled, ticketEnabled, reportEnabled, reportDisabled, suggestDisabled, suggestEnabled, noPermission, levelDisabled, levelEnabled, logDisabled, logEnabled, roleDisabled, roleEnabled, musicDisabled, musicEnabled };