const discord = require('discord.js');
const { MessageEmbed } = require('discord.js');
const colors = require('./colors.json');
const prefix = "/";

const timeoutNoTime = new MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":x: No Time!")
    .setDescription("You did not specify a valid time. Format: 1d, 2h, 1mo etc.")
    .setTimestamp();
const invalidEmojis = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":x: Error!")
    .setDescription("You used an invalid emoji!")
    .setTimestamp()
const notClosed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":x: This ticket isn't closed")
    .setTimestamp()
const notATicket = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":x: You are not inside of a ticket!")
    .setTimestamp()
const tooLong = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(`:x: Too Long!`)
    .setDescription("Your response/reason was too long to fit in a message embed!")
    .setTimestamp()
const QuizSentenceNone = new discord.MessageEmbed()
    .setColor(colors.TICKET_CLOSE)
    .setTitle("No questions found!")
    .setDescription("This is a bug.")
    .setTimestamp()
const closeTicketEmbed = new discord.MessageEmbed()
    .setColor(colors.TICKET_CLOSE)
    .setTitle("Close Ticket")
    .setDescription("Close or delete this ticket using the buttons below this message.")
    .setTimestamp()
const noOwner = new MessageEmbed()
    .setTitle(`:x: Not your ticket!`)
    .setDescription(`This is not your tickets and/or you do not have the **BAN MEMBERS** permission.`)
    .setTimestamp()
    .setColor(colors.COLOR)
const noMSG = new MessageEmbed()
    .setTitle(":x: Could not find a message with that id!")
    .setDescription("Either the ID is invalid or the message was deleted.")
    .setColor(colors.COLOR)
    .setTimestamp()
const pollDisabled = new discord.MessageEmbed()
    .setTitle(":x: Polls are disabled in this guild!")
    .setColor(colors.COLOR)
    .setTimestamp()
const shuffledQueue = new MessageEmbed()
    .setTitle(":twisted_rightwards_arrows: Shuffled the Queue!")
    .setColor(colors.COLOR)
    .setTimestamp()
const stoppedQueue = new MessageEmbed()
    .setTitle(":stop_button: Stopped the queue!")
    .setColor(colors.COLOR)
    .setTimestamp()
const skippedSong = new MessageEmbed()
    .setTitle(":track_next: Skipped a song!")
    .setColor(colors.COLOR)
    .setTimestamp()
const noValidSeek = new discord.MessageEmbed()
    .setTitle("Invalid number!")
    .setDescription("Please enter a number of seconds to seek the song to.")
    .setColor(colors.COLOR)
    .setTimestamp()
const noValidMode = new discord.MessageEmbed()
    .setTitle(":x: Invalid mode")
    .setDescription("Please pick either \`0 - OFF, 1 - REPEAT SONG or 2 - REPEAT QUEUE\`")
    .setColor(colors.COLOR)
    .setTimestamp()
const pausedQueue = new discord.MessageEmbed()
    .setTitle(":pause_button: Paused the Queue!")
    .setDescription("Use `/resume` to start playing again.")
    .setColor(colors.COLOR)
    .setTimestamp()
const resumedQueue = new discord.MessageEmbed()
    .setTitle(":play_pause: Resumed the Queue!")
    .setDescription("Use `/pause` to pause the music stream again.")
    .setColor(colors.COLOR)
    .setTimestamp()
const noSongs = new discord.MessageEmbed()
    .setTitle(":x: No Songs!")
    .setDescription("There are no songs playing/in the queue, play one using `/play song: [song]`!")
    .setColor(colors.COLOR)
    .setTimestamp()
const debugError = new discord.MessageEmbed()
    .setTitle(":x: No Permission!")
    .setDescription("This command can only be used by QuaBot developers.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setURL("https://discord.quabot.xyz")
const CatNoFiles = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to attach files!")
    .setDescription("Please contact an administrator to fix this.")
    .setColor(colors.COLOR)
    .setTimestamp()
const CatScanning = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":mag: Searching for cat images!")
const CoinFlipping = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Tossing the coin... :coin:")
const DogNoFiles = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to attach files!")
    .setDescription("Please contact an administrator to fix this.")
    .setTimestamp()
    .setColor(colors.COLOR)
const DogScanning = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":mag: Searching for dog images!")
const MemeNoAttach = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to attach files!")
    .setDescription("Please contact an administrator to fix this.")
    .setTimestamp()
    .setColor(colors.COLOR);
const MusicDisabled = new discord.MessageEmbed()
    .setTitle(":x: Music is disabled in this guild!")
    .setColor(colors.COLOR)
    .setDescription("Please contact an admin to change this setting.")
    .setTimestamp();
const MemeScanning = new discord.MessageEmbed()
    .setTitle(":mag: Searching for memes!")
    .setColor(colors.COLOR)
const TypeNoSentence = new discord.MessageEmbed()
    .setTitle(":x: Could not find a sentence!")
    .setDescription("Please report this using `/quabot`!")
    .setColor(colors.COLOR)
    .setTimestamp()
const DonateEmbed = new discord.MessageEmbed()
    .setTitle("Support Quabot")
    .setColor(colors.COLOR)
    .setURL("https://quabot.xyz/")
    .setDescription("Quabot is a non-profit project, that takes up money, for hosting, and time, for coding. By donating to us you directly support us! :)")
    .addField("Donate", "[Click here](https://paypal.me/joascraft) for the link.")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setTimestamp();
const HelpMain = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTimestamp()
    .setTitle("Select a category of commands using the dropdown.")
    .setDescription("When selecting a category you'll get a detailed list of commands within that category.")
    .setThumbnail("https://i.imgur.com/jgdQUul.png");
const LBNoXP = new discord.MessageEmbed()
    .setTitle(":x: That user does not have XP!")
    .setDescription('The user doesn\'t have xp or there are no users with xp.')
    .setColor(colors.COLOR)
    .setTimestamp();
const LBDisabled = new discord.MessageEmbed()
    .setTitle(":x: Levels are disabled in this guild!")
    .setDescription("Please contact an admin to change this setting.")
    .setTimestamp()
    .setColor(colors.COLOR)
const addedDatabase = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Database updated!")
    .setDescription("Added this guild or a user to the database.")
    .setTimestamp()
    .setColor(colors.COLOR)
const errorMain = new discord.MessageEmbed()
    .setTitle(":x: There was an error!")
    .setDescription("The developers have been alerted of this error, it will be fixed soon.")
    .setFooter("Tip: You can report bugs and leave suggestions with `/quabot`.")
    .setTimestamp()
    .setColor(colors.COLOR)
const PingGetting = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setDescription(":clock7:  Getting ping...");
const SupportEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setTimestamp()
    .setDescription("**Do you need support?**\n\nIf you run into an issue, have a question or just wanna chat with people you can join our support discord.\nBot downtime, updates and more are also announced here.\n\nInvite: https://discord.gg/Nwu9DNjYa9");
const NotInVC = new discord.MessageEmbed()
    .setTitle(":x: You need to be in a voice channel to play songs!")
    .setTimestamp()
    .setDescription('You need to be in a voice channel and in the same voice channel as quabot to play music.')
    .setColor(colors.COLOR);
const MusicIsDisabled = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":x: Music is disabled in this guild!")
    .setTimestamp()
    .setDescription("Please ask an administrator to change this setting.");
const NotPlaying = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":x: There is no music playing!")
    .setTimestamp()
    .setFooter("Tip: use `/filter` to change the way your music plays")
    .setDescription("Play something with `/play`");
const PauseQueue = new discord.MessageEmbed()
    .setTitle(`:pause_button: Paused the queue!`)
    .setTimestamp()
    .setFooter("Tip: use `/volume` to change the stream's volume")
    .setDescription('Use `/resume` to continue the music stream.')
    .setColor(colors.COLOR);
const banNoPermsBot = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to ban members!")
    .setTimestamp()
    .setDescription("Please contact an administrator to fix this.")
    .setColor(colors.COLOR);
const banNoPermsUser = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to ban members!")
    .setTimestamp()
    .setColor(colors.COLOR);
const banNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user you want to ban!")
    .setTimestamp()
    .setFooter("Tip: you can use `/config` to enable features disabled by default")
    .setColor(colors.COLOR)
const unbanNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please specify a user-id you want to unban!")
    .setTimestamp()
    .setFooter("Please note you need a **user-id**")
    .setColor(colors.COLOR)
const banImpossible = new discord.MessageEmbed()
    .setTitle(":x: Failed to ban, you cannot ban this user!")
    .setTimestamp()
    .setColor(colors.COLOR)
const PunsishmentsOthers = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to view punishments of other users!")
    .setTimestamp()
    .setFooter("You need the `BAN MEMBERS` permission")
    .setColor(colors.COLOR)
const clearpunNoType = new discord.MessageEmbed()
    .setTitle(":question: Please enter a type of punishment to clear: `warn, kick, mute or ban`!")
    .setTimestamp()
    .setFooter(":x: This feature is unsupported, please do not expect any results :x:")
    .setColor(colors.COLOR);
const clearpunNoMember = new discord.MessageEmbed()
    .setTitle(":x: Please mention a user to clear the warnings of!")
    .setTimestamp()
    .setColor(colors.COLOR);
const kickNoPermsClient = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to kick members!")
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
    .setColor(colors.COLOR)
const kickNoPermsUser = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to kick members!")
    .setTimestamp()
    .setFooter("Tip: make you own server so you can use all commands and explore all features")
    .setColor(colors.COLOR)
const kickNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user you want to kick!")
    .setTimestamp()
    .setColor(colors.COLOR)
const kickImpossible = new discord.MessageEmbed()
    .setTitle(":x: Failed to kick, you cannot ban this user!")
    .setTimestamp()
    .setFooter('Tip: use `/config` to change settings')
    .setColor(colors.COLOR)
const muteNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user to mute!")
    .setTimestamp()
    .setColor(colors.COLOR);
const muteNoRoleManage = new discord.MessageEmbed()
    .setDescription(":x: I do not have permission to manage roles!")
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
    .setColor(colors.COLOR);
const muteNoPermsUser = new discord.MessageEmbed()
    .setDescription(":x: You do not have permission to mute members!")
    .setColor(colors.COLOR);
const reportNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user to report!")
    .setTimestamp()
    .setColor(colors.COLOR);
const reportNoSelf = new discord.MessageEmbed()
    .setTitle(":x: You cannot report yourself!")
    .setTimestamp()
    .setFooter("You fool, that's not how the system works")
    .setColor(colors.COLOR);
const reportNoContent = new discord.MessageEmbed()
    .setTitle(":x: Please enter something you wish to report this user for!")
    .setTimestamp()
    .setColor(colors.COLOR);
const reportsDisabled = new discord.MessageEmbed()
    .setTitle(":x: This guild has reports disabled!")
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
    .setColor(colors.COLOR);
const reportNoChannel = new discord.MessageEmbed()
    .setTitle(":x: This guild doesn't have a report logging channel setup!")
    .setColor(colors.COLOR)
    .setDescription("Please contact an admin to change this setting.")
    .setFooter(`Use \`/config\` to fix this`)
    .setTimestamp();
const banNoTime = new discord.MessageEmbed()
    .setTitle(":question: Please enter a time to ban this user!")
    .setTimestamp()
    .setFooter("Tip: make a guild and explore all features, there are a lot!")
    .setColor(colors.COLOR);
const muteNoManageRoles = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to manage roles!")
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
    .setColor(colors.COLOR);
const muteUserNoPerms = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to ban members!")
    .setTimestamp()
    .setColor(colors.COLOR);
const muteNoTime = new discord.MessageEmbed()
    .setTitle(":question: Please enter a time to ban this user!")
    .setTimestamp()
    .setColor(colors.COLOR);
const banNoUserFound = new discord.MessageEmbed()
    .setTitle(":x: Could not find that user!")
    .setTimestamp()
    .setDescription("Please try again.")
    .setColor(colors.COLOR);
const notBanned = new discord.MessageEmbed()
    .setTitle(":x: That user is not banned!")
    .setTimestamp()
    .setColor(colors.COLOR);
const unmuteNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user to mute!")
    .setTimestamp()
    .setColor(colors.COLOR);
const unmuteBotNoRoles = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to manage roles!")
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
    .setColor(colors.COLOR);
const unmuteUserNoPerms = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to mute members!")
    .setTimestamp()
    .setColor(colors.COLOR);
const warnNoPerms = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to warn members!")
    .setTimestamp()
    .setFooter(`You need the \`BAN MEMBERS\` permission`)
    .setColor(colors.COLOR);
const warnNoUserToWarn = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user you want to warn!")
    .setColor(colors.COLOR)
    .setTimestamp()
const warnNotHigherRole = new discord.MessageEmbed()
    .setTitle(":x: You cannot warn someone with a higher role than you!")
    .setColor(colors.COLOR)
    .setTimestamp()
const suggestDisabled = new discord.MessageEmbed()
    .setTitle(":x: Suggestions are disabled in this guild!")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
const noSuggestChannelConfigured = new discord.MessageEmbed()
    .setTitle(":x: There is no suggestion log channel setup!")
    .setColor(colors.COLOR)
    .setDescription("Please contact an admin to change this setting.")
    .setTimestamp()
    .setFooter("Tip: use `/config` to set it up")
const noPollChannelConfigured = new discord.MessageEmbed()
    .setTitle(":x: There is no polls log channel setup!")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
    .setFooter("Tip: use `/config` to set it up")
const suggestTooShort = new discord.MessageEmbed()
    .setTitle(":x: Your suggestion is too short!")
    .setTimestamp()
    .setColor(colors.COLOR)
const ticketsDisabled = new discord.MessageEmbed()
    .setTitle(":x: Tickets are disabled in this guild!")
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
    .setColor(colors.COLOR)
const PornScanning = new discord.MessageEmbed()
    .setTitle(":mag: Scanning the web for porn!")
    .setDescription(":x: THIS IS A JOKE, DONT KILL ME <3 :x:")
    .setColor(colors.COLOR);
const noWelcomeChannel = new discord.MessageEmbed()
    .setTitle("New member!")
    .setTimestamp()
    .setFooter("Tip: use `/config` to set it up")
    .setDescription("Did not send a message, no channel is setup!")
    .setColor(colors.COLOR)
const funEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Fun Commands")
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands give funny pictures, games and more.\n
    **${prefix}cat** - Get an image of a cat.
    **${prefix}coin** - Flip a coin.
    **${prefix}dog** - Get an image of a dog.
    **${prefix}meme** - Get a meme.
    **${prefix}quiz** - Play a quiz.
    **${prefix}rps** - Play rock, paper, scissors.
    **${prefix}type** - Play a typing game.`);
const infoEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Info Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setTimestamp()
    .setDescription(`These commands are used to get information about loads of different things.\n    
    **${prefix}announcement** - Latest quabot news.
    **${prefix}help** - List commands and their descriptions.
    **${prefix}info** - Information about the bot.
    **${prefix}leaderboard** - Server XP's leadersboard.
    **${prefix}nick** - Change the nickname of a user.
    **${prefix}online** -  View activity list.
    **${prefix}ping** - Get bot ping.
    **${prefix}rank** - Get level and XP points.
    **${prefix}roles** - List of roles in this guild.
    **${prefix}serverinfo** - Server information.
    **${prefix}stats** - Bot statistics.
    **${prefix}support** - Bot's support discord.
    **${prefix}uptime** - Bot's uptime.
    **${prefix}userinfo** - Information about a user.
    `)
const musicEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Music Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setTimestamp()
    .setDescription(`These commands are all commands related to music.\n
    **${prefix}autoplay** - Toggle autoplay.
    **${prefix}nowplaying** - Information about the playing song.
    **${prefix}filter** - Toggle filters.
    **${prefix}join** - Make bot join your vc.
    **${prefix}leave** - Make bot leave your vc.
    **${prefix}pause** - Pause the stream.
    **${prefix}play** - Play a song.
    **${prefix}queue** - Get music queue.
    **${prefix}repeat** - Alter repeat mode.
    **${prefix}resume** - Resume the stream.
    **${prefix}seek** - Seek to a point in the song.
    **${prefix}shuffle** - Shuffle queue.
    **${prefix}skip** - Skip the playing song.
    **${prefix}stop** - Stop the music stream.
    **${prefix}volume** - Change volume.
    `)
const miscEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Misc Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setTimestamp()
    .setDescription(`These commands are just general commands that dont fit the descrition of the ones above.\n
    **${prefix}avatar** - Get a user's avatar.
    **${prefix}divide** - Divide two numbers.
    **${prefix}members** - Get the guild's membercount.
    **${prefix}multiply** - Multiply two numbers.
    **${prefix}power** - Get a number to the power of a number.
    **${prefix}servericon** - Get the guild's icon.
    **${prefix}subtract** - Subtract two numbers.
    **${prefix}sum** - Sum of two numbers.
    `)
const moderationEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Moderation Commands")
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands are used to punish users and moderate the server.\n
    **${prefix}ban** - Ban a member.
    **${prefix}kick** - Kick a member.
    **${prefix}timeout** - Timeout a member.
    **${prefix}punishments** - View a member's punishments.
    **${prefix}report** - Report a user.
    **${prefix}tempban** - Temporarily ban a member.
    **${prefix}unban** - Unban a member.
    **${prefix}warn** - Warn a member.
    `)
const managementEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Management Commands")
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands are used by managers to clear channels, start giveaways and more.\n
    **${prefix}admin** - Send a "open ticket" message.
    **${prefix}clear** - Clear an amount of messages.
    **${prefix}config** - Configure quabot.
    **${prefix}lock** - Lock a channel.
    **${prefix}mention** - Ping everyone.
    **${prefix}reactionrole** - Create and delete reactionroles.
    **${prefix}unlock** - Get bot ping.
    `)
const supportHEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Support Commands")
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands can be used by members to seek support, make suggestions and more.\n
    **${prefix}add** - Add a user to your ticket.
    **${prefix}close** - Close a ticket.
    **${prefix}delete** - Delete a ticket.
    **${prefix}endpoll** - End the voting on a poll.
    **${prefix}endsuggestion** - End the voting on a suggestion.
    **${prefix}poll** - Start a poll.
    **${prefix}quabot** - Leave suggestions and bug reports.
    **${prefix}remove** - Remove users from a ticket.
    **${prefix}reopen** - Reopen a ticket.
    **${prefix}settopic** - Change a ticket topic.
    **${prefix}suggest** - Make a suggestion.
    **${prefix}ticket** - Open a ticket.
    **${prefix}transcript** - Make a ticket transcript.
    `)
const reportSucces = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTimestamp()
    .setTimestamp()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("You have succesfully filed a report.")
const suggestSucces = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTimestamp()
    .setTitle(":white_check_mark: Succes!")
    .setTimestamp()
    .setDescription("You have succesfully left a suggestion.")
const optionsEmbed = new discord.MessageEmbed()
    .setTitle("Quabot configuration")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("Configure quabot to be perfect for your server. Select a category using the dropdown.")
const noPerms = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to do that!")
    .setTimestamp()
    .setColor(colors.COLOR)
const iNoPerms = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to do that!")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setDescription("Please contact an admin to change this setting.")
const toggleEmbed = new discord.MessageEmbed()
    .setTitle("Toggle Features")
    .setDescription("Use the dropdown to select a setting you wish to change!")
    .setColor(colors.COLOR)
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setFooter("(Page 1/2)")
    .setTimestamp();
const toggleEmbed2 = new discord.MessageEmbed()
    .setTitle("Toggle Features")
    .setDescription("Use the dropdown to select a setting you wish to change!")
    .setColor(colors.COLOR)
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setFooter("(Page 2/2)")
    .setTimestamp();
const levelsDisabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Disabled Level System succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setFooter("If you want to change this, please run the command again.")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const levelsEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled Level System succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setFooter("If you want to change this, please run the command again.")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const logsDisabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Disabled Logging System succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const logsEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Enabled Logging System succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const roleDisabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Disabled the Join role system succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const roleEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled the Join role system succesfully.")
    .setFooter("If you want to change this, please run the command again.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const pollsDisabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Disabled the Polls System succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const pollEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Enabled the Polls System succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const musicDisabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Disabled music succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const musicEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled music succesfully.")
    .setFooter("If you want to change this, please run the command again.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const reportDisabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Disabled music succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const reportEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled music succesfully.")
    .setFooter("If you want to change this, please run the command again.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const suggestDisabled1 = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Disabled suggestions succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const suggestEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled suggestions succesfully.")
    .setFooter("If you want to change this, please run the command again.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const ticketDisabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Disabled tickets succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const ticketEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled tickets succesfully.")
    .setFooter("If you want to change this, please run the command again.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const welcomeDisabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setFooter("If you want to change this, please run the command again.")
    .setDescription("Disabled welcome messages succesfully.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const welcomeEnabled = new discord.MessageEmbed()
    .setTitle(":white_check_mark: Succes!")
    .setDescription("Enabled welcome messages succesfully.")
    .setFooter("If you want to change this, please run the command again.")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const channelEmbed = new discord.MessageEmbed()
    .setTitle("Configure Channels")
    .setDescription("Use the dropdown to select a setting you wish to change!")
    .setColor(colors.COLOR)
    .setTimestamp()
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
const roleEmbed = new discord.MessageEmbed()
    .setTitle("Configure Role Names")
    .setDescription("Use the dropdown to select a setting you wish to change!")
    .setColor(colors.COLOR)
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setTimestamp()
    .setFooter("Eg. For mutes and join roles.");
const disabledLevelUp = new discord.MessageEmbed()
    .setTitle("Disabled Level Up Channel")
    .setColor(colors.COLOR)
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setTimestamp()
    .setDescription("Messages will now be sent in the users message channel at that time.")

const embedClose1 = new discord.MessageEmbed()
    .setColor(colors.TICKET_DELETE)
    .setTitle("Delete Ticket")
    .setDescription("Delete this ticket using the buttons below this message.")
    .setTimestamp()
const guildUserBanEmbed = new discord.MessageEmbed()
    .setTitle("User Banned")
    .setColor(colors.BAN_COLOR)
    .setTimestamp()

module.exports = { guildUserBanEmbed, timeoutNoTime, invalidEmojis, supportHEmbed, notClosed, notATicket, tooLong, QuizSentenceNone, embedClose1, closeTicketEmbed, noOwner, pollEnabled, pollsDisabled, noPollChannelConfigured, noMSG, iNoPerms, pollDisabled, stoppedQueue, skippedSong, noValidSeek, disabledLevelUp, noSongs, shuffledQueue, resumedQueue, pausedQueue, noValidMode, debugError, roleEmbed, channelEmbed, MusicIsDisabled, welcomeDisabled, welcomeEnabled, ticketDisabled, ticketEnabled, suggestEnabled, suggestDisabled1, toggleEmbed2, reportEnabled, reportDisabled, musicDisabled, musicEnabled, roleEnabled, roleDisabled, logsDisabled, logsEnabled, levelsDisabled, levelsEnabled, toggleEmbed, noPerms, optionsEmbed, moderationEmbed, suggestSucces, reportSucces, managementEmbed, miscEmbed, funEmbed, infoEmbed, musicEmbed, noWelcomeChannel, PornScanning, ticketsDisabled, suggestTooShort, noSuggestChannelConfigured, suggestDisabled, warnNotHigherRole, warnNoPerms, warnNoUserToWarn, unmuteNoUser, unmuteUserNoPerms, unmuteBotNoRoles, notBanned, unbanNoUser, banNoUserFound, muteNoTime, muteNoManageRoles, muteUserNoPerms, banNoTime, reportNoChannel, reportsDisabled, reportNoContent, reportNoSelf, reportNoUser, muteNoUser, muteNoRoleManage, muteNoPermsUser, kickImpossible, kickNoPermsClient, kickNoUser, kickNoPermsUser, clearpunNoType, clearpunNoMember, PunsishmentsOthers, banNoPermsBot, banNoPermsUser, banNoUser, banImpossible, PauseQueue, NotPlaying, MusicDisabled, NotInVC, CatNoFiles, CatScanning, PingGetting, SupportEmbed, CoinFlipping, DogNoFiles, DogScanning, MemeScanning, MemeNoAttach, TypeNoSentence, DonateEmbed, HelpMain, LBNoXP, LBDisabled, addedDatabase, errorMain }