const discord = require('discord.js');
const colors = require('./colors.json');
const prefix = "/";

const CatNoFiles = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to attach files!")
    .setColor(colors.COLOR)
const CatScanning = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":mag: Scanning the web for the cutest cat! :cat:")
const CoinFlipping = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Tossing the coin... :coin:")
const DogNoFiles = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to attach files!")
    .setColor(colors.COLOR)
const DogScanning = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":mag: Scanning the web for the cutest dog! :dog: ")
const MemeNoAttach = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to attach files!")
    .setColor(colors.COLOR);
const MemeScanning = new discord.MessageEmbed()
    .setTitle(":mag: Scanning for the best memes... :joy:")
    .setColor(colors.COLOR)
const TypeNoSentence = new discord.MessageEmbed()
    .setTitle(":x: Could not find a sentence!")
    .setColor(colors.COLOR)
const DonateEmbed = new discord.MessageEmbed()
    .setTitle("Support Quabot :thumbsup:")
    .setColor(colors.COLOR)
    .setDescription("Quabot is a non-profit project, that takes up money and time. By donating to us via paypal you directly support us! :)")
    .addField("Donate", "[Click here](https://paypal.me/joascraft) for the link.")
const HelpMain = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Select a category of commands using the dropdown.")
    .setDescription("When selecting a category you'll get a detailed list of commands within that category.")
    .setThumbnail("https://i.imgur.com/jgdQUul.png");
const LBNoXP = new discord.MessageEmbed()
    .setTitle(":x: That user does not have XP!")
    .setColor(colors.COLOR);
const LBDisabled = new discord.MessageEmbed()
    .setTitle(":x: Levels are disabled in this guild!")
    .setColor(colors.COLOR)
const addedDatabase = new discord.MessageEmbed()
    .setTitle(":white_check_mark: This server is now added to our database.")
    .setColor(colors.COLOR)
const errorMain = new discord.MessageEmbed()
    .setTitle(":x: There was an error!")
    .setDescription("This issue is probably database related, please contact someone at our support discord.\nhttps://discord.gg/Nwu9DNjYa9")
    .setColor(colors.COLOR)
const PingGetting = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setDescription(":clock7:  Getting ping...");
const SupportEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription("**Do you need support?**\n\nIf you run into an issue, have a question or just wanna chat with people you can join our support discord.\nBot downtime, updates and more are also announced here.\n\nInvite: https://discord.gg/Nwu9DNjYa9");
const NotInVC = new discord.MessageEmbed()
    .setTitle(":x: You need to be in a voice channel to play songs!")
    .setColor(colors.COLOR);
const MusicDisabled = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":x: Music is disabled in this guild!");
const NotPlaying = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle(":x: There is no music playing!");
const PauseQueue = new discord.MessageEmbed()
    .setTitle(`:pause_button: Paused the queue!`)
    .setColor(colors.COLOR);
const banNoPermsBot = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to ban members!")
    .setColor(colors.COLOR);
const banNoPermsUser = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to ban members!")
    .setColor(colors.COLOR);
const banNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user you want to ban!")
    .setColor(colors.COLOR)
const unbanNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please specify a user-id you want to unban!")
    .setColor(colors.COLOR)
const banImpossible = new discord.MessageEmbed()
    .setTitle(":x: Failed to ban, you cannot ban this user!")
    .setColor(colors.COLOR)
const PunsishmentsOthers = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to view punishments of other users!")
    .setColor(colors.COLOR)
const clearpunNoType = new discord.MessageEmbed()
    .setTitle(":question: Please enter a type of punishment to clear: `warn, kick, mute or ban`!")
    .setColor(colors.COLOR);
const clearpunNoMember = new discord.MessageEmbed()
    .setTitle(":x: Please mention a user to clear the warnings of!")
    .setColor(colors.COLOR);
const kickNoPermsClient = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to kick members!")
    .setColor(colors.COLOR)
const kickNoPermsUser = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to kick members!")
    .setColor(colors.COLOR)
const kickNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user you want to kick!")
    .setColor(colors.COLOR)
const kickImpossible = new discord.MessageEmbed()
    .setTitle(":x: Failed to kick, you cannot ban this user!")
    .setColor(colors.COLOR)
const muteNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user to mute!")
    .setColor(colors.COLOR);
const muteNoRoleManage = new discord.MessageEmbed()
    .setDescription(":x: I do not have permission to manage roles!")
    .setColor(colors.COLOR);
const muteNoPermsUser = new discord.MessageEmbed()
    .setDescription(":x: You do not have permission to mute members!")
    .setColor(colors.COLOR);
const reportNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user to report!")
    .setColor(colors.COLOR);
const reportNoSelf = new discord.MessageEmbed()
    .setTitle(":x: You cannot report yourself!")
    .setColor(colors.COLOR);
const reportNoContent = new discord.MessageEmbed()
    .setTitle(":x: Please enter something you wish to report this user for!")
    .setColor(colors.COLOR);
const reportsDisabled = new discord.MessageEmbed()
    .setTitle(":x: This guild has reports disabled!")
    .setColor(colors.COLOR);
const reportNoChannel = new discord.MessageEmbed()
    .setTitle(":x: This guild doesn't have a report logging channel setup!")
    .setColor(colors.COLOR);
const banNoTime = new discord.MessageEmbed()
    .setTitle(":question: Please enter a time to ban this user!")
    .setColor(colors.COLOR);
const muteNoManageRoles = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to manage roles!")
    .setColor(colors.COLOR);
const muteUserNoPerms = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to ban members!")
    .setColor(colors.COLOR);
const muteNoTime = new discord.MessageEmbed()
    .setTitle(":question: Please enter a time to ban this user!")
    .setColor(colors.COLOR);
const banNoUserFound = new discord.MessageEmbed()
    .setTitle(":x: Could not find that user!")
    .setColor(colors.COLOR);
const notBanned = new discord.MessageEmbed()
    .setTitle(":x: That user is not banned!")
    .setColor(colors.COLOR);
const unmuteNoUser = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user to mute!")
    .setColor(colors.COLOR);
const unmuteBotNoRoles = new discord.MessageEmbed()
    .setTitle(":x: I do not have permission to manage roles!")
    .setColor(colors.COLOR);
const unmuteUserNoPerms = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to mute members!")
    .setColor(colors.COLOR);
const warnNoPerms = new discord.MessageEmbed()
    .setTitle(":x: You do not have permission to warn members! `BAN_MEMBERS`")
    .setColor(colors.COLOR);
const warnNoUserToWarn = new discord.MessageEmbed()
    .setTitle(":question: Please mention a user you want to warn!")
    .setColor(colors.COLOR)
const warnNotHigherRole = new discord.MessageEmbed()
    .setTitle(":x: You cannot warn someone with a higher role than you!")
    .setColor(colors.COLOR)
const suggestDisabled = new discord.MessageEmbed()
    .setTitle(":x: Suggestions are disabled in this guild!")
    .setColor(colors.COLOR)
const noSuggestChannelConfigured = new discord.MessageEmbed()
    .setTitle(":x: There is no suggestion log channel setup!")
    .setColor(colors.COLOR)
const suggestTooShort = new discord.MessageEmbed()
    .setTitle(":x: Your suggestion is too short!")
    .setColor(colors.COLOR)
const ticketsDisabled = new discord.MessageEmbed()
    .setTitle(":x: Tickets are disabled in this guild!")
    .setColor(colors.COLOR)
const PornScanning = new discord.MessageEmbed()
    .setTitle(":mag: Scanning the web for porn!")
    .setColor(colors.COLOR);
const noWelcomeChannel = new discord.MessageEmbed()
    .setTitle("New member!")
    .setDescription("Did not send a message, no channel is setup!")
    .setColor(colors.COLOR)
const funEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Fun Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands give funny pictures, games and more.\n\n**${prefix}coin** - When using this command you will flip a virtual coin.\n**${prefix}cat** - When you use this command you will recieve a cute picture of a cat.\n**${prefix}dog** - By using this command you recieve picture of a dog.\n**${prefix}meme** - When you use this command you get a random meme from a subreddit.\n**${prefix}rps** - With this command you can play rock, paper, scissors with the bot.\n**${prefix}type** - Play a game that makes you type words/sentences in 15 seconds.`);
const infoEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Info Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands are used to get information about loads of different things.\n\n**${prefix}server** - By using this command you get the server name.\n**${prefix}donate** - This command is used to get info about donations to quabot.\n**${prefix}help** - By using this command you will get a list of commands or see how to use them.\n**${prefix}info** - When using this command you will recieve a list of bot information.\n**${prefix}leaderboard** - This command allows you to view a leaderbord of levels of a server.\n**${prefix}online** -  This will display the amount of users on the guild with every presence.\n**${prefix}ping** - When using this command you will recieve your ping.\n**${prefix}serverinfo** - When you use this command, you can see a list of information about the server.\n**${prefix}uptime ** - When using this command, the current online time of the bot is displayed.\n**${prefix}userinfo** - When you use this command you get a list of information about a user.\n**${prefix}prefix** - Get the server prefix.\n**${prefix}stats** - View the discord bot stats and hardware.\n**${prefix}rank** - Get your current amount of levels and XP points.`)
const musicEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Music Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands are all commands related to music.\n\n**${prefix}autoplay** - By using this command you can toggle wether or not songs should automaticaly play.\n**${prefix}nowplaying** - This command displays the song that is currently playing.\n**${prefix}pause** - When using this command you will pause the currently playing song.\n**${prefix}play** - Play a song to your liking.\n**${prefix}queue** - View the current queue of songs.\n**${prefix}repeat** - Toggle if songs should repeat or not.\n**${prefix}resume** - Contiune to play music if it's been previously stopped.\n**${prefix}seek** - Go to a specific point in th currently playing song.\n**${prefix}shuffle** - Shuffle the queue to a new order.\n**${prefix}skip** - Skip the currently playing song and go to the next one.\n**${prefix}status** - Get the status of the bot (music related (volume etc.)).\n**${prefix}stop** - Stop the queue and the playing of the current song.\n**${prefix}volume** - Change the volume of the currently playing music.\n**${prefix}join** - Make quabot join your voice channel.`)
const miscEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Misc Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands are just general commands that dont fit the descrition of the ones above.\n**${prefix}avatar** - By using this command you will be able to view either your own profile picture or another users'\n**${prefix}members** - When you use this command you will see the amount of members on a server.\n**${prefix}nick** - By using this command you'll be able to change your nickname.\n**${prefix}emotes** - !emotes - When using this command you will recieve a list of emotes.`)
const moderationEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Moderation Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands are used to punish users and moderate the server.\n\n**${prefix}ban** - This command allows you to permanently ban a user from the guild your in.\n**${prefix}kick** - This command allows you to kick a user from the guild your in.\n**${prefix}mute** - By using this command you will be able to mute any user in your guild.\n**${prefix}tempban** - By using this command you can ban a user for a specified amount of time.\n**${prefix}tempmute** - By using this command you can mute a user for a specified amount of time.\n**${prefix}unban** - By using this command you can unban any user using their user-id.\n**${prefix}unmute** - You can unmute any person on your guild.\n**${prefix}warn** - Warn a specified user with a custom reason.\n**${prefix}punsihments** - View your punishments.\n**${prefix}clearpunishments** - Clear a users's punishments (or just one).`);
const managementEmbed = new discord.MessageEmbed()
    .setColor(colors.COLOR)
    .setTitle("Management Commands")
    .setThumbnail("https://i.imgur.com/jgdQUul.png")
    .setDescription(`These commands are used by managers to clear channels, start giveaways and more.\n\n**${prefix}clear** - By using this command you can delete a large amount of messages at once.\n**${prefix}config** - Change server settings.\n**${prefix}end** - When you use thins command correctly you will force-end a running giveaway.\n**${prefix}giveaway** - By using this command you will be able to start a giveaway.\n**${prefix}lockdown** - By using this command you will lockdown a channel to stop members from sending messages.\n**${prefix}reroll** - When using this command you can pick a new winner for a giveaway.`)


module.exports = { moderationEmbed, managementEmbed, miscEmbed, funEmbed, infoEmbed, musicEmbed, noWelcomeChannel, PornScanning, ticketsDisabled, suggestTooShort, noSuggestChannelConfigured, suggestDisabled, warnNotHigherRole, warnNoPerms, warnNoUserToWarn, unmuteNoUser, unmuteUserNoPerms, unmuteBotNoRoles, notBanned, unbanNoUser, banNoUserFound, muteNoTime, muteNoManageRoles, muteUserNoPerms, banNoTime, reportNoChannel, reportsDisabled, reportNoContent, reportNoSelf, reportNoUser, muteNoUser, muteNoRoleManage, muteNoPermsUser, kickImpossible, kickNoPermsClient, kickNoUser, kickNoPermsUser, clearpunNoType, clearpunNoMember, PunsishmentsOthers, banNoPermsBot, banNoPermsUser, banNoUser, banImpossible, PauseQueue, NotPlaying, MusicDisabled, NotInVC, CatNoFiles, CatScanning, PingGetting, SupportEmbed, CoinFlipping, DogNoFiles, DogScanning, MemeScanning, MemeNoAttach, TypeNoSentence, DonateEmbed, HelpMain, LBNoXP, LBDisabled, addedDatabase, errorMain}